# Generated by Django 5.0 on 2023-12-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_earn'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Earn',
        ),
    ]
