# Generated by Django 5.0 on 2024-01-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cartitem_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('easypesa', 'EasyPesa'), ('jazzcash', 'JazzCash'), ('cashondelivery', 'Cash On Delivery')], default='cashondelivery', max_length=20),
        ),
    ]
