# Generated by Django 5.0 on 2024-01-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_dashboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard',
            new_name='LandingPage',
        ),
    ]
