# Generated by Django 5.0 on 2024-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_dashboard_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='img1',
            field=models.ImageField(blank=True, default='defaultUser.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='img2',
            field=models.ImageField(blank=True, default='defaultUser.jpg', null=True, upload_to=''),
        ),
    ]
