# Generated by Django 5.0 on 2024-01-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_landingpage_img1_landingpage_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('cashondelivery', 'Cash On Delivery')], default='cashondelivery', max_length=20),
        ),
    ]
